version: "3"
services:
  sns-mysql:
    platform: linux/x86_64
    image: amd64/mysql:8.0.34
    container_name: sns-db
    environment:
      MYSQL_ROOT_PASSWORD: chlqus310@
      MYSQL_DATABASE: sns
    ports:
      - "3306:3306"
    volumes:
      - ../sns-mysql:/var/lib/mysql
      - ../sns-mysql-conf:/etc/mysql/conf.d
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
    restart: always